name = "cloudflare-fluentbit-logger"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
# 生产环境配置（敏感信息请使用 wrangler secret put 设置）
# FLUENTBIT_URL = "http://your-fluentbit-server-ip:9880/cf.logs"
